### PR TITLE
View Sqlite in Browser

### PR DESCRIPTION
**Pull request by ryneeverett**
I've been trying to streamline the workflow a bit and after a few
different experiments this one turned out best.

For the record I wouldn't recommend using bundled source from cdn like
this but it's an easy way to demonstrate the functionality.

image

image

### CODE REVIEW

**Comment by obsidianforensics** [comment]
This looks amazing! I've wanted to be able to view the results in the UI, but it seemed like way too much work to build. This is a great way to get that functionality in there (plus enabling SQL queries!)

**Comment by ryneeverett** [comment]
I'm glad you're interested because I'd like to get this on track to be merged. The only thing I know of that needs to be settled to get this out of "Draft" status is a better way of distributing the javascript. I don't know of an ideal solution for distributing static assets in python applications but here's a few options off the top of my head:

- CDN: I'm not a fan of this option because I don't think there's any good reason to require an internet connection to use hindsight. In fact for certain forensics applications there's a good reason to disable network access.
- Assets in Hindsight Repo: Many python applications I've seen simply check frontend dependencies into the repo. This works ok as they're usually not frequently update. However, I'm not a big fan of this as (a) it's basically impossible to audit automatically (b) these files are a huge clutter of irrelevance in your repo (e.g., making it harder to search within the code base without getting irrelevant javascript).
- Assets Package: Another common pattern I see is having a separate repo and package for assets (e.g. "hindsight-assets"). This does alleviate the point about clutter but not so much the source trust/auditing issue.
- Separate Installation Step: I don't know of any way to run an arbitrary script on `pip install` -- you can add arbitrary code to setup.py but I don't believe it would work on a wheel installation. However, every other aspect of the project than the in-browser-viewer page would work without the javascript and I could probably even make the button on the results page conditional on the javascript being installed. Although this is the only idea that leaves the project unable to be completely installed with pip, it's my preferred solution of those I've thought of so far.

Note: This really only addresses the distribution of the assets. There are still choices to be made regarding how and where to bundle the assets -- for example in this draft the asset pointed to at the CDN is a 28,000 line bundle of all recursive dependencies whereas I would prefer all dependencies be fetched from source at install-time -- but I believe this issue is orthogonal.

Thoughts?

**Comment by obsidianforensics** [comment]
I think a separate installation step is fine. As you said, Hindsight would remain functional otherwise without it, and I think it isn't that much to ask for the separate install if the user wants that functionality. Having the button not appear (or grayed-out or something) as an indicator for the user would also be a nice tough too. 

In my mind, the compiled Windows executable is what users who want the simplest (none) install procedure are most likely to use, and I can include the JS stuff in that one so they still won't need to worry about it.

**Comment by obsidianforensics** [comment]
Looks great! Thanks again for your work.

**Comment by obsidianforensics** [comment]
I'm not sure how familiar you are with sqlite-view.js, but do you know of any way to escape or not render code in the cells? When viewing values that contain scripts or css, they are rendering - this isn't ideal from a viewing perspective and obviously has security implications.

**Comment by ryneeverett** [comment]
Sorry if I should have disclosed this but I thought it was fairly obvious -- I published sqlite-view specifically for this use case. It's an abstraction of [sqlite-viewer](https://github.com/inloop/sqlite-viewer) so while I didn't originate much of it I'm fairly familiar.

That said, good catch -- there is indeed no sanitization at present. I should have time to get this done and released in the next day or two. Tracking issue: https://gitlab.com/ryneeverett/sqlite-view/-/issues/5.

**Comment by obsidianforensics** [comment]
No worries - I saw you owned sqlite-view, but didn't want to assume knowledge about sql.js and sqlite-viewer. I'm much less familiar with the whole js ecosystem than Python's. Thanks for working on this.

If you run the latest code from master, it parses out Local Storage & File System items, and these typically have plenty of examples of things to be sanitized (if that would be helpful for you).

**Pull request merged**
